---
# tasks file for elk_rsyslog
  - name: elk | install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: elk | sinc time-zone and restart chronyd
    template:
       src: /usr/share/zoneinfo/Europe/Moscow
       dest: /etc/localtime
    systemd:
      name: nginx.service
      state: reloaded
