---
# tasks file for elk_rsyslog
  - name: elk | install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: elk | restart chronyd
    shell: systemctl restart chronyd
