---
# tasks file for web
  - name: web | install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: web | sinc time-zone
    template:
       src: /usr/share/zoneinfo/Europe/Moscow
       dest: /etc/localtime

  - name: web | restart chronyd
    shell: systemctl restart chronyd
    tags:
       - restart_chrony

  - name: web | Install NGINX package from EPEL Repo
    yum:
       name: nginx
       state: latest
    notify:
       - restart nginx
    tags:
       - nginx-package