---
# tasks file for web
  - name: web | install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: web | sinc time-zone and restart chronyd
    template:
       src: /usr/share/zoneinfo/Europe/Moscow
       dest: /etc/localtime
    systemd:
      name: nginx.service
      state: reloaded