---
# tasks file for web
  - name: web | install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: web | sinc time-zone
    template:
       src: /usr/share/zoneinfo/Europe/Moscow
       dest: /etc/localtime

  - name: web | restart chronyd
    shell: systemctl restart chronyd
    tags:
       - restart_chrony

  - name: web | Install NGINX package from EPEL Repo
    yum:
       name: nginx
       state: latest
    tags:
       - nginx-package

  - name: web | copy nginx.conf
    template:
       src: ./files/nginx.conf.j2
       dest: /etc/nginx/nginx.conf

  - name: web | test config nginx
    shell: nginx -t

  - name: web | start NGINX 
    systemd:
      name: nginx
      enabled: yes
      state: started
    tags:
       - nginx-package